### ISSUE TITLE
Cannot open website with iPad

### ISSUE THREAD

**Issue by Yoejay** [gomocalc/gomocalc.github.io#11]
Hello ,@dhbloo
Thank you for your nice job for gomoku.
I cannot load the website(https://gomocalc.com/)  with my iPad.The chessboard can be displayed,buttons not available.But its OK with PC or Android.
Device info:
A1893,iPad (6th generation)
IOS 15.3.1
chrome,safari

Thank you

**Comment by dhbloo** [comment]
Hello, this seems a network issue. Can you try to change the network environment (eg. switch to another wifi) and also try a different browser (eg. chrome), to see whether the problem is solved? Also, you can try [www.gomocalc.com](https://www.gomocalc.com/) (note the www. before the domain name), which in some case might be more accessable.

**Comment by dhbloo** [comment]
Support on iOS is now fixed. Please refresh your browser cache and it should works fine now
